baseURL = "https://www.haroonakram.co.uk"
languageCode = "en-us"
title = "Haroon's Den"

theme = "hugo-ficurinia"

author = "Gabriele Musco"
copyright = "Gabriele Musco - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."

paginate = 5
summaryLength = 30

[params]
    description = "My Cyber Security (& Whatever i find interesting) blog"
    author = "Haroon Akram"
    logo = "/logo.svg"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"
    showRss = false
    imageInArticlePreview = true
    enableFeatured = true           # use feature: true in the header of each article
    enableShareOnFediverse = false
    posts = "CTFs posts"          # shows both the posts and CTF articles on the home page
    showPostsLink = true
    extraContentDirs = ["CTFs", "projects"]
    showSinglePageAsHome = false
    homeSinglePage = "/home/"

    enableRelatedArticles = false
    relatedArticlesNum = 0 
    forceRedirect = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.icons]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/haroon-akram/"
        weight = 10
    [[menu.icons]]
        identifier = "tryhackme"
        name = "TryHackMe"
        url = "https://tryhackme.com/p/Mist97"
        weight = 10

